name: estimagic_presentation

channels:
  - defaults
  - conda-forge
  - janosg

dependencies:

  - python=3.7
  - pandas=0.24
  - pip=19.0.3
  - numpy=1.16
  - pygmo=2.10
  - bokeh=1.1
  - scipy=1.2.1
  - estimagic=0.0.4
  - skillmodels=0.0.55
  - jupyter
  - mkl-service
